# [6] 넘파이(numpy)
## [6.0] 넘파이 기초

In [2]:
# numpy 불러와서 사용해보기
import numpy as np

#1-d tensor data (just a list of observations)
np.array([1, 5, 7, 6])

array([1, 5, 7, 6])

In [3]:
# np.array를 수행하면 데이터 형식이 통일화된다
np.array([1.25, 1, 5, 7])

array([1.25, 1.  , 5.  , 7.  ])

In [4]:
# numpy의 유용한 함수(방법)들
# 초기치를 구는 데 사용한다.
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [65]:
# numpy의 유용한 함수(방법)들
# 초기치를 구는 데 사용한다.
np.ones([2,3], dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.arange(0, 10, 2)   # 0 포함 O, 10 포함 X

array([0, 2, 4, 6, 8])

In [66]:
# 5등분해라
np.linspace(0, 1, 5)  # 0 포함 O, 10 포함 O

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### seed값을 동일하게 해줘야 값이 일치하는 것을 확인할 수 있다

In [11]:
# random number generator seed
np.random.seed(12)
np.random.random((3,3))        # 3 by 3 U(0,1) 생성

array([[0.15416284, 0.7400497 , 0.26331502],
       [0.53373939, 0.01457496, 0.91874701],
       [0.90071485, 0.03342143, 0.95694934]])

In [12]:
# random number generator seed
np.random.seed(12)
np.random.random((3,3))        # 3 by 3 U(0,1) 생성

array([[0.15416284, 0.7400497 , 0.26331502],
       [0.53373939, 0.01457496, 0.91874701],
       [0.90071485, 0.03342143, 0.95694934]])

In [13]:
# without seed
np.random.random((3,3))        # 3 by 3 U(0,1) 생성

array([[0.13720932, 0.28382835, 0.60608318],
       [0.94422514, 0.85273554, 0.00225923],
       [0.52122603, 0.55203763, 0.48537741]])

In [5]:
np.random.normal(0, 1, (3,3))  # 3 by 3 N(0,1) 생성

array([[-0.42069204, -0.7060276 ,  0.58535808],
       [ 0.13978644,  2.73781428,  1.11674795],
       [ 1.57453814, -0.08586679,  0.47673663]])

In [6]:
np.random.randint(0, 10, (3,3)) # 3 by 3 정수(0-9) 생성

array([[9, 0, 0],
       [9, 8, 9],
       [6, 1, 8]])

In [22]:
# np random이라는 library 밑에 RandomState라는 class 
rg = np.random.RandomState(40)  # np.random.RandomState 클래스를 rg로 객체화
rg.normal(0, 1, (3,3))

array([[-0.6075477 , -0.12613641, -0.68460636],
       [ 0.92871475, -1.84440103, -0.46700242],
       [ 2.29249034,  0.48881005,  0.71026699]])

In [36]:
# array의 객체화
import numpy as np
np.random.seed(1)

x = np.random.randint(10, size=(2,3,4))
# size 확인할 때 TIP, 첫번째 값은 observation수로 인식하라
# 그말은 즉, (3,4)matrix가 두개 인것 처럼 해석하라
print(x)
print(x.ndim)
print(x.shape)
print(x.size)

[[[5 8 9 5]
  [0 0 1 7]
  [6 9 2 4]]

 [[5 2 4 2]
  [4 7 7 9]
  [1 7 0 6]]]
3
(2, 3, 4)
24


In [39]:
print('original')
print(x)
print('-'*30)

print('flatten')
print(x.flatten())
print('-'*30)

print('reshape')
print(x.reshape(2,3,4))

original
[[[5 8 9 5]
  [0 0 1 7]
  [6 9 2 4]]

 [[5 2 4 2]
  [4 7 7 9]
  [1 7 0 6]]]
------------------------------
flatten
[5 8 9 5 0 0 1 7 6 9 2 4 5 2 4 2 4 7 7 9 1 7 0 6]
------------------------------
reshape
[[[5 8 9 5]
  [0 0 1 7]
  [6 9 2 4]]

 [[5 2 4 2]
  [4 7 7 9]
  [1 7 0 6]]]


In [40]:
# array 접근과 편집(slicing)
x = np.array([0,3,5,2,4,6])  # 1차원
print(x[1])

3


In [41]:
help(np.newaxis)

Help on NoneType object:

class NoneType(object)
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |  
 |  __repr__(self, /)
 |      Return repr(self).



In [42]:
print(x, '\n') #1-d vector

x1 =x[np.newaxis, :] # 2-d vector(행백터)
print(x1, '\n')

x2=x[:,np.newaxis] # 2-d vector(열백터)
print(x2, '\n')

x3=x.reshape(1,6) # 2-d vector(행백터)
print(x3, '\n')

x4=x.reshape(6,1) # 2-d vector(열백터)
print(x4, '\n')

x5=np.reshape(x,(6,1)) # reshape 다른 표기법
print(x5, '\n')

x6=x5.flatten()
print(x6, '\n')

[0 3 5 2 4 6] 

[[0 3 5 2 4 6]] 

[[0]
 [3]
 [5]
 [2]
 [4]
 [6]] 

[[0 3 5 2 4 6]] 

[[0]
 [3]
 [5]
 [2]
 [4]
 [6]] 

[[0]
 [3]
 [5]
 [2]
 [4]
 [6]] 

[0 3 5 2 4 6] 



In [43]:
x[1:3]   

array([3, 5])

In [44]:
x[1:-2]

array([3, 5, 2])

In [18]:
x[::2]    # x[start:stop:step], x[start:stop:step,start:stop:step]

array([0, 5, 4])

In [19]:
x[:2]

array([0, 3])

In [20]:
x[::-1]   # 역순으로

array([6, 4, 2, 5, 3, 0])

In [21]:
x[5::-2] # 역순으로 두칸식

array([6, 2, 3])

In [50]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x.shape, '\n')
print(x, '\n')
print(x[:2,:],'\n')
print(x[:2, :2])

(3, 3) 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2 3]
 [4 5 6]] 

[[1 2]
 [4 5]]


In [23]:
x[:, 0]   # 첫째 열

array([1, 4, 7])

In [24]:
x[0, :]   # 첫째 행

array([1, 2, 3])

In [25]:
x[0]

array([1, 2, 3])

In [51]:
x_list = list(x)
# list에서는 x[1][2]로 같은 동작을 수행하였음
x[1][2] # list 호출방법

6

In [52]:
x[1, 2] # array 호출 방법 

6

### 객체화와 카피
- 일반적으로 데이터를 슬라이싱해오면 수정시 원본 데이터에도 영향 O
- 이를 방지하기 위해 개체를 따로 복제해서 오는 매서드인 .copy()를 이용하면 해결 가능

In [53]:
x[0, 0] = 99
x

array([[99,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [54]:
x1 = x[:2, :2]
x1

array([[99,  2],
       [ 4,  5]])

In [55]:
x1[0, 1] = 99
x1

array([[99, 99],
       [ 4,  5]])

In [56]:
print(x)  # x1을 수정하면 x에도 반영이 됨. ∵뷰 형태로 x와 동일한 객체를 참조

[[99 99  3]
 [ 4  5  6]
 [ 7  8  9]]


In [57]:
print(id(x));print(id(x1))    # 주소는 x와 다름

2018511549984
2018512845440


In [32]:
x1_copy = x[:2, :2].copy()
x1_copy[0, 0] = 1000  # x에 영향을 주지 않음
print(x)

[[99 99  3]
 [ 4  5  6]
 [ 7  8  9]]


## [6.1] numpy의 차원 변경, 분할, 덧붙이기

In [61]:
# 차원 변경
import numpy as np

# 1-d tensor
x = np.array([1, 2, 3])
print(x)
x.reshape(1, 3)
print(x)
x.reshape(3,1)
print(x)

# 2-d tensor
x.reshape((1, 3))  # 2차원 행벡터화([]가 한 겹 더 생겼음)
print(x[np.newaxis, :])
x.reshape((3, 1))  # 2차원 열벡터화
print(x[:, np.newaxis])

[1 2 3]
[1 2 3]
[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [35]:
# 3-d tensor
x = np.random.randint(10, size=(3,3,4))
print(x)
print('---------------------------')
# 2-d tensor
x1 = x.reshape((3, 12))  # 3 by 4 행렬의 각 행을 옆으로 붙임
print(x1)
x2=x.reshape((-1,12))
print(np.shape(x2))
x.shape[1]

[[[9 9 7 6]
  [9 1 0 1]
  [8 8 3 9]]

 [[8 7 3 6]
  [5 1 9 3]
  [4 8 1 4]]

 [[0 3 9 2]
  [0 4 9 2]
  [7 7 9 8]]]
---------------------------
[[9 9 7 6 9 1 0 1 8 8 3 9]
 [8 7 3 6 5 1 9 3 4 8 1 4]
 [0 3 9 2 0 4 9 2 7 7 9 8]]
(3, 12)


3

In [36]:
# 분할
x = [1, 2, 3, 4, 5, 6, 7, 8]
x1, x2, x3 = np.split(x, [2,6])
print(x1, x2, x3)
x1[0] = 100  # 분할된 변수의 변경은 x에 반영되지 않음
print(x1)

[1 2] [3 4 5 6] [7 8]
[100   2]


In [37]:
x = np.random.random((4, 4));print(x)

[[0.46923853 0.09617226 0.90337017 0.11949047]
 [0.52479938 0.083623   0.91686133 0.91044838]
 [0.29893011 0.58438912 0.56591203 0.61393832]
 [0.95653566 0.26097898 0.23101542 0.53344849]]


In [38]:
x1, x2 = np.vsplit(x, [2])  # 세로를 분할
print(x1)
print('--------------------------------------------------')
print(x2)

[[0.46923853 0.09617226 0.90337017 0.11949047]
 [0.52479938 0.083623   0.91686133 0.91044838]]
--------------------------------------------------
[[0.29893011 0.58438912 0.56591203 0.61393832]
 [0.95653566 0.26097898 0.23101542 0.53344849]]


In [39]:
y1, y2 = np.hsplit(x, [2])  # 가로를 분할
print(y1)
print('---------------------------')
print(y2)

[[0.46923853 0.09617226]
 [0.52479938 0.083623  ]
 [0.29893011 0.58438912]
 [0.95653566 0.26097898]]
---------------------------
[[0.90337017 0.11949047]
 [0.91686133 0.91044838]
 [0.56591203 0.61393832]
 [0.23101542 0.53344849]]


In [40]:
# 덧붙이기
x = np.array([1, 2])
y = np.array([2, 3])
z = np.array([4, 5])

# observation 늘리기
np.concatenate([x, y, z])

array([1, 2, 2, 3, 4, 5])

In [41]:
xx = np.array([[1,2,3], [4,5,6]])
yy = np.array([[2,4,6], [8,7,6]])
print(np.concatenate([xx, yy]))          # 아래로 붙임
print('---------------------------')
print(np.concatenate([xx, yy], axis=1))  # 옆으로 붙임

[[1 2 3]
 [4 5 6]
 [2 4 6]
 [8 7 6]]
---------------------------
[[1 2 3 2 4 6]
 [4 5 6 8 7 6]]


In [42]:
zz = np.array([55, 66, 77])
np.vstack([zz, xx])  # 세로로 쌓기. np.concatenate([zz.reshape((1,3)), xx])과 결과 동일

array([[55, 66, 77],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [43]:
ww = np.array([[100], [200]])  # 열벡터
np.hstack([ww, xx])  # 가로로 쌓기

array([[100,   1,   2,   3],
       [200,   4,   5,   6]])

## [6.2] numpy 연산

In [45]:
# broadcasting
x = np.array([1, 2, 3, 4])
print(x+3)
print(x-3)
print(x*3)
print(x/3)
print(x**3)
print(-(0.5*x+1)**2)

[4 5 6 7]
[-2 -1  0  1]
[ 3  6  9 12]
[0.33333333 0.66666667 1.         1.33333333]
[ 1  8 27 64]
[-2.25 -4.   -6.25 -9.  ]


In [46]:
# broadcasting
print(np.exp(x))
print(np.power(3, x))
print(np.log(x))
print(np.log2(x))
print(np.log10(x))

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 3  9 27 81]
[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]
[0.         0.30103    0.47712125 0.60205999]


In [47]:
M = np.ones((3, 3))
print(M)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [48]:
M1 = M + 1
print(M1)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [49]:
a = np.array([1, 2, 3])
M2 = M + a  # row by row로 연산 수행
print(M2)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [50]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a);print(b)
print('---------------------------')
print(a+b)

[0 1 2]
[[0]
 [1]
 [2]]
---------------------------
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [63]:
# 기초통계량 계산
np.random.seed(13)
x = np.random.randint(10, size=(3,4))
print(x)

[[2 0 0 6]
 [2 4 9 3]
 [4 2 6 5]]


In [65]:
# 연산의 axis는 across의 개념으로 생각
# 합
print(np.sum(x))           # 원소의 총 합계
print(np.sum(x, axis = 1)) # 원소의 행 총 합계
print(np.sum(x, axis = 0)) # 원소의 열 총 합계

# 최소, 최대
print(np.min(x, axis=1))   # 각 행의 최소값
print(np.max(x, axis=1))   # 각 행의 최대값

# 평균, 표준편차
print(np.mean(x, axis=0))  # 각 열의 평균
print(np.std(x, axis=0))   # 각 열의 표준편차

43
[ 8 18 17]
[ 8  6 15 14]
[0 2 2]
[6 9 6]
[2.66666667 2.         5.         4.66666667]
[0.94280904 1.63299316 3.74165739 1.24721913]


In [68]:
# 표준편차
x_std = (x - np.mean(x, axis=0))/np.std(x, axis=0)
print(x_std)
print('-'*50)
print(np.sum(x_std, axis=0))

[[-0.70710678 -1.22474487 -1.33630621  1.06904497]
 [-0.70710678  1.22474487  1.06904497 -1.33630621]
 [ 1.41421356  0.          0.26726124  0.26726124]]
--------------------------------------------------
[ 4.44089210e-16  0.00000000e+00  1.11022302e-16 -7.77156117e-16]


## [6.2] 논리 인덱싱(Boolean indexing)과 순서 정렬(Sorting) ###

In [54]:
import numpy as np
x = np.array([[1,2,3,4], [5,6,7,8]]); print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [69]:
print(x >= 5)
print(np.sum(x>=5)) # 조건을 중족하는 것의 합
print(np.sum(x>=5, axis=1))  # 각 행별로 연산
print(np.sum(x>=5, axis=0))  # 각 열별로 연산

[[False False False  True]
 [False False  True False]
 [False False  True  True]]
4
[1 1 2]
[0 0 2 2]


In [73]:
print(np.any(x>100))         # 하나라도 있는가
print(np.all(x==7))           # 전부다 만족하는가
print(np.all(x<7, axis=0))   # 각 열별로 연산

False
False
[ True  True False  True]


In [74]:
# 논리 인덱싱
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(x)
y = np.array([1,0,1,0])
print(y)
print(y==0)
print(x[y==0, :])  # y=0인 행과 모든 열(논리식에 의한 호출)
print('---------------------------')
print(x[:, y==0])  # 모든 행과 y=0인 열

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[1 0 1 0]
[False  True False  True]
[[ 5  6  7  8]
 [13 14 15 16]]
---------------------------
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [58]:
# array를 활용한 인덱싱
x = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
print(x)
ind1 = np.array([2, 3, 8])
ind2 = np.array([[2,1,3], [5,2,7]])
x1 = x[ind1]
x2 = x[ind2]
print(x1)
print('---------------------------')
print(x2)

[11 22 33 44 55 66 77 88 99]
[33 44 99]
---------------------------
[[33 22 44]
 [66 33 88]]


In [84]:
# not(~) array를 활용한 인덱싱
x = np.arange(12).reshape((3,4))
print(x)

ind = np.array([1,3])
print('ind : {}'.format(ind))
print('~ind : {}'.format(~ind))

xx = x[:,~ind]
print(xx)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
ind : [1 3]
~ind : [-2 -4]
[[ 2  0]
 [ 6  4]
 [10  8]]


In [92]:
x = np.arange(12).reshape((3,4))
print(x)
y1 = np.array([1, 2, 2])
y2 = np.array([2, 0, 1])
print('y1: {}'.format(y1))
print('y2: {}'.format(y2))
print('---------------------------')
print(x[[1,2,2], :])
print(x[:, [2,0,1]])
print(x[[1,2,2], [2,0,1]])
print(x[y1, y2])
print('---------------------------')
# 인덱싱에서의 브로드캐스팅 : 책 참고
y3=y1[:,np.newaxis]
print(y3)
print(x[y3, :])
print(x[y3, y2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
y1: [1 2 2]
y2: [2 0 1]
---------------------------
[[ 4  5  6  7]
 [ 8  9 10 11]
 [ 8  9 10 11]]
[[ 2  0  1]
 [ 6  4  5]
 [10  8  9]]
[6 8 9]
[6 8 9]
---------------------------
[[1]
 [2]
 [2]]
[[[ 4  5  6  7]]

 [[ 8  9 10 11]]

 [[ 8  9 10 11]]]
[[ 6  4  5]
 [10  8  9]
 [10  8  9]]


### 순서 정렬

In [93]:
x = np.array([2, 4, 3, 1, 5])
x

array([2, 4, 3, 1, 5])

In [95]:
# 순서 정렬
print(np.sort(x))

[1 2 3 4 5]


In [94]:
# sort한 것의 index
ind = np.argsort(x) 
print(ind) 

[3 0 2 1 4]


In [63]:
import numpy as np
x=np.random.randint(1,10, size=(2,3,4))
x

array([[[5, 3, 1, 4],
        [6, 4, 7, 6],
        [2, 3, 9, 9]],

       [[7, 3, 5, 6],
        [8, 4, 6, 9],
        [4, 9, 6, 2]]])

In [64]:
x1=x[:,-1,:]
x1

array([[2, 3, 9, 9],
       [4, 9, 6, 2]])