In [1]:
import pandas as pd
import numpy as np

In [3]:
# 데이터 불러오기. y값은 이미 범주형으로 되어있음.
dat_wine=pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/'
                     'wine/wine.data',header=None)
dat_wine.head()
dat_wine.columns = ['class label', 'alchohol', 'malic acid', 'ash', 
                    'alcalinity of ash', 'magnesium', 'total phenols', 
                    'flavanoids', 'nonflavanoid phenols', 
                    'proanthocyanins', 'color intensity', 'hue', 
                    'OD208', 'proline']  # Column names
print('class label:', np.unique(dat_wine['class label']))  # Class 출력
dat_wine.head()

class label: [1 2 3]


class label  alchohol  malic acid   ash  alcalinity of ash  magnesium  \
0            1     14.23        1.71  2.43               15.6        127   
1            1     13.20        1.78  2.14               11.2        100   
2            1     13.16        2.36  2.67               18.6        101   
3            1     14.37        1.95  2.50               16.8        113   
4            1     13.24        2.59  2.87               21.0        118   

   total phenols  flavanoids  nonflavanoid phenols  proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   color intensity   hue  OD208  proline  
0             5.64  1.04   3.92     1065  
1             4.38  1.05   3.40     1050  
2             5.68  1.03   3.17     1185  
3             7.80  0.86   3.45     1480  
4             4.32  1.04   2.93      735

In [4]:
# 전체 data를 training set과 test set으로 split
from sklearn.model_selection import train_test_split
X, y = dat_wine.iloc[:,1:].values, dat_wine.iloc[:,0].values
X_train, X_test, y_train,y_test = \
    train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)

In [5]:
# 표준화
from sklearn.preprocessing import StandardScaler
std = StandardScaler()
X_train_std = std.fit_transform(X_train)
X_test_std = std.transform(X_test)

In [6]:
# Logistic Regression with L2 or L1 Regularization
from sklearn.linear_model import LogisticRegression
lr2_10 = LogisticRegression(penalty='l2', C=10.0)  # L2 with C(=1/λ)=10
lr2_1 = LogisticRegression(penalty='l2', C=1.0)    # L2 with C(=1/λ)=1
lr2_0_1 = LogisticRegression(penalty='l2', C=0.1)  # L2 with C(=1/λ)=0.1
lr1_10 = LogisticRegression(penalty='l1', C=10.0)  # L1 with C(=1/λ)=10
lr1_1 = LogisticRegression(penalty='l1', C=1.0)    # L1 with C(=1/λ)=1
lr1_0_1 = LogisticRegression(penalty='l1', C=0.1)  # L1 with C(=1/λ)=0.1

In [9]:
# 규제화 방법(L2 or L1)과 규제강도(λ)를 바꿔가며 accuracy score 계산
lr2_10.fit(X_train_std, y_train)
print('Training accuracy with L2 and λ=0.1:', lr2_10.score(X_train_std, y_train))
print('Test accuracy with L2 and λ=0.1:', lr2_10.score(X_test_std, y_test))

lr2_1.fit(X_train_std, y_train)  # warning..
print('Training accuracy with L2 and λ=1:', lr2_1.score(X_train_std, y_train))
print('Test accuracy with L2 and λ=1:', lr2_1.score(X_test_std, y_test))

lr2_0_1.fit(X_train_std, y_train)
print('Training accuracy with L2 and λ=10:', lr2_0_1.score(X_train_std, y_train))
print('Test accuracy with L2 and λ=10:', lr2_0_1.score(X_test_std, y_test))

lr1_10.fit(X_train_std, y_train)
print('Training accuracy with L1 and λ=0.1:', lr1_10.score(X_train_std, y_train))
print('Test accuracy with L1 and λ=0.1:', lr1_10.score(X_test_std, y_test))

lr1_1.fit(X_train_std, y_train)
print('Training accuracy with L1 and λ=1:', lr1_1.score(X_train_std, y_train))
print('Test accuracy with L1 and λ=1:', lr1_1.score(X_test_std, y_test))

lr1_0_1.fit(X_train_std, y_train)
print('Training accuracy with L1 and λ=10:', lr1_0_1.score(X_train_std, y_train))
print('Test accuracy with L1 and λ=10:', lr1_0_1.score(X_test_std, y_test))

Training accuracy with L2 and λ=0.1: 1.0
Test accuracy with L2 and λ=0.1: 0.9629629629629629
Training accuracy with L2 and λ=1: 1.0
Test accuracy with L2 and λ=1: 0.9814814814814815
Training accuracy with L2 and λ=10: 0.9919354838709677
Test accuracy with L2 and λ=10: 0.9814814814814815
Training accuracy with L1 and λ=0.1: 1.0
Test accuracy with L1 and λ=0.1: 0.9814814814814815
Training accuracy with L1 and λ=1: 1.0
Test accuracy with L1 and λ=1: 0.9814814814814815
Training accuracy with L1 and λ=10: 0.9838709677419355
Test accuracy with L1 and λ=10: 1.0


C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to

In [10]:
# L2 규제의 규제강도(C=1/λ)를 바꿔가며 계수 추정치 관찰
print(lr2_10.intercept_)
print(lr2_1.intercept_)
print(lr2_0_1.intercept_)

print(lr2_10.coef_)
print(lr2_1.coef_)
print(lr2_0_1.coef_)

[-1.95775485 -2.03400782 -3.43291968]
[-1.21122348 -1.03039089 -1.97016349]
[-0.60105075 -0.40659682 -0.88778119]
[[ 2.31301856  0.42623793  0.88915733 -2.72742063  0.34471977  0.57063457
   1.5328249  -0.05747067 -0.14460937  0.02365977 -0.1387799   1.54453754
   2.51006889]
 [-2.4473801  -1.00394827 -2.00966039  1.87532324 -0.35077231 -1.05421584
   1.79723557  0.73213183  0.6214013  -2.34983446  1.65715682  0.1387643
  -3.41020463]
 [ 0.6567932   0.46268852  1.37035647  0.34767553  0.30329156  0.47280507
  -3.25015231 -0.70851215 -0.5273707   1.92694485 -1.61435627 -1.42974821
   0.11678842]]
[[ 1.30549004  0.14549881  0.46036028 -1.44931922  0.10031419  0.36298361
   0.87213708 -0.11270049  0.02097189  0.09455712  0.05891572  0.8160453
   1.64325979]
 [-1.52090137 -0.57645877 -0.92554937  0.93057203 -0.32301482 -0.32640468
   0.67685016  0.31393307  0.31558446 -1.26644027  0.89364797  0.11339036
  -1.69368203]
 [ 0.36275758  0.42896676  0.49386343  0.31296385  0.264319   -0.0694720

In [11]:
# L2 규제의 규제강도(C=1/λ)를 바꿔가며 계수 추정치 관찰
print(lr1_10.intercept_)
print(lr1_1.intercept_)
print(lr1_0_1.intercept_)

print(lr1_10.coef_)
print(lr1_1.coef_)
print(lr1_0_1.coef_)

[-2.14035866 -2.65922403 -4.16476189]
[-1.11958913 -1.13559733 -2.22622892]
[-0.29617765 -0.08175121 -0.78575087]
[[ 2.94105456  0.28661411  1.10478325 -3.13661938  0.244986    0.
   1.89714188  0.          0.          0.          0.          1.8919487
   3.25251407]
 [-2.86050792 -1.01088098 -2.63913443  1.99728475  0.         -0.94773025
   1.78186294  0.72894868  1.12998626 -3.44013092  2.28398555  0.
  -5.19649767]
 [ 0.90803487  0.20038068  1.91121041  0.          0.20378065  0.18872926
  -5.50689492 -0.9494814  -0.02848173  2.70832306 -1.49302574 -0.84299314
   0.        ]]
[[ 1.41320331  0.          0.27838963 -1.36300459  0.          0.
   1.27114553  0.          0.          0.          0.          0.7122173
   2.22002694]
 [-1.68928458 -0.37315879 -0.8247154   0.68070422 -0.11987273  0.
   0.3959537   0.01144807  0.24951005 -1.42631508  1.05996578  0.
  -2.23082137]
 [ 0.          0.23194873  0.50743267  0.          0.16131275  0.
  -2.48984944 -0.11935498  0.          1.65069

In [7]:
lr2_10.fit(X_train, y_train)
print('Training accuracy with L2 and λ=0.1:', lr2_10.score(X_train, y_train))
print('Test accuracy with L2 and λ=0.1:', lr2_10.score(X_test, y_test))

lr2_1.fit(X_train, y_train)  # warning..
print('Training accuracy with L2 and λ=1:', lr2_1.score(X_train, y_train))
print('Test accuracy with L2 and λ=1:', lr2_1.score(X_test, y_test))

lr2_0_1.fit(X_train, y_train)
print('Training accuracy with L2 and λ=10:', lr2_0_1.score(X_train, y_train))
print('Test accuracy with L2 and λ=10:', lr2_0_1.score(X_test, y_test))

lr1_10.fit(X_train, y_train)
print('Training accuracy with L1 and λ=0.1:', lr1_10.score(X_train, y_train))
print('Test accuracy with L1 and λ=0.1:', lr1_10.score(X_test, y_test))

lr1_1.fit(X_train, y_train)
print('Training accuracy with L1 and λ=1:', lr1_1.score(X_train, y_train))
print('Test accuracy with L1 and λ=1:', lr1_1.score(X_test, y_test))

lr1_0_1.fit(X_train, y_train)
print('Training accuracy with L1 and λ=10:', lr1_0_1.score(X_train, y_train))
print('Test accuracy with L1 and λ=10:', lr1_0_1.score(X_test, y_test))

Training accuracy with L2 and λ=0.1: 1.0
Test accuracy with L2 and λ=0.1: 0.9444444444444444
Training accuracy with L2 and λ=1: 0.9838709677419355
Test accuracy with L2 and λ=1: 0.9444444444444444
Training accuracy with L2 and λ=10: 0.9758064516129032
Test accuracy with L2 and λ=10: 0.9259259259259259
Training accuracy with L1 and λ=0.1: 1.0
Test accuracy with L1 and λ=0.1: 0.9074074074074074
Training accuracy with L1 and λ=1: 0.9838709677419355
Test accuracy with L1 and λ=1: 0.9074074074074074
Training accuracy with L1 and λ=10: 0.9354838709677419
Test accuracy with L1 and λ=10: 0.8888888888888888


C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to

In [8]:
print(lr2_10.intercept_)
print(lr2_1.intercept_)
print(lr2_0_1.intercept_)

print(lr2_10.coef_)
print(lr2_1.coef_)
print(lr2_0_1.coef_)

[-0.96456004  1.34118396 -0.22390307]
[-0.16655119  0.26945958 -0.07022366]
[-0.02988443  0.05684191 -0.02613036]
[[-8.35654939e-01  1.44150350e+00  1.46570959e+00 -1.27574191e+00
   2.09578947e-02  9.54417242e-01  3.00222626e+00 -7.24568499e-02
  -1.22897003e+00 -5.54461321e-01 -1.84306873e-02  6.28614504e-01
   2.67981633e-02]
 [ 1.09359574e+00 -2.12095717e+00 -1.21322442e+00  7.34605497e-01
  -1.75690138e-02 -1.04233634e+00  1.23716271e+00  2.85603369e+00
   1.60402367e+00 -2.48226700e+00  3.26535993e+00 -6.66781906e-01
  -2.21810800e-02]
 [-7.02348476e-01  1.19098753e+00  5.88127902e-01  4.03900064e-02
   7.27945504e-02 -3.70618302e-01 -3.76294649e+00 -6.02758148e-01
  -7.46352348e-01  1.33638830e+00 -1.36735959e+00 -2.11442785e+00
   2.97823296e-03]]
[[-3.58983950e-01  4.10637468e-01  3.53872093e-01 -7.42979348e-01
  -3.36933385e-02  5.44683231e-01  1.12999767e+00 -5.75279878e-02
   5.03329511e-02 -1.89873020e-01  7.55818484e-03  6.14639419e-01
   2.00108374e-02]
 [ 5.83708283e-01

In [9]:
print(lr1_10.intercept_)
print(lr1_1.intercept_)
print(lr1_0_1.intercept_)

print(lr1_10.coef_)
print(lr1_1.coef_)
print(lr1_0_1.coef_)

[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[[-1.01302850e+00  2.39608807e+00  1.71991521e-01 -1.86127869e+00
   8.34950377e-02  0.00000000e+00  7.14119679e+00  0.00000000e+00
  -2.97774639e+00 -8.18214103e-01  0.00000000e+00  0.00000000e+00
   3.49411930e-02]
 [ 1.31679390e+00 -2.73038551e+00 -3.38001837e+00  9.41289186e-01
   0.00000000e+00 -1.95012089e+00  1.91790955e+00  1.23238533e+01
   2.58858839e+00 -3.24670367e+00  4.31646082e+00 -5.15270908e-01
  -2.73681581e-02]
 [-2.78642772e-01  1.40323545e+00  0.00000000e+00  3.31841490e-02
   1.17547347e-01  0.00000000e+00 -7.98095839e+00  0.00000000e+00
   0.00000000e+00  1.24944131e+00 -2.20232349e+00 -3.76082391e+00
  -6.33896232e-04]]
[[-2.34793075e-02  8.11723037e-02  0.00000000e+00 -7.05407269e-01
  -4.59876204e-02  0.00000000e+00  1.97035783e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.76174386e-02]
 [ 5.87514555e-01 -1.21890126e+00  0.00000000e+00  4.28854104e-01
   2.44013384e-02  0.00000000e+0